version: 2


models:
  - name: dim_date
    columns:
      - name: date_id
        tests: 
          - not_null
          - unique
  
  - name: dim_location
    columns:
      - name: location_id
        tests: 
          - not_null
          - unique
  
  
  - name: dim_product
    columns:
      - name: product_id
        tests: 
          - not_null
          - unique
  
  
  - name: dim_store
    columns:
      - name: store_id
        tests: 
          - not_null
          - unique
  

  - name: dim_user
    columns:
      - name: sk_user_id
        tests: 
          - not_null
          - unique
  
  
  - name: dim_fx_rate_usd
    columns:
      - name: from_currency
        tests: 
          - not_null
          - unique
  
      - name: rate_to_usd
        tests: 
          - not_null
    
  - name: fact_sales_order_tt
    columns:
      - name: sk_fact_sales
        tests: 
          - not_null
          - unique
      - name: order_id
        tests:
          - not_null        
      - name: product_id
        tests:
          - not_null 
      - name: date_id
        tests:
          - not_null 
      - name: sk_user_id
        tests:
          - not_null 
      - name: store_id
        tests:
          - not_null 
      - name: location_id
        tests:
          - not_null 

  #relationship (skip product due to o data product not full as fail crawl )

      - name: date_id
        tests: 
          - relationships:
              to: ref('dim_date')
              field: date_id
        
      - name: store_id
        tests:
          - relationships:
              to: ref('dim_store')
              field: store_id

      - name: location_id
        tests:
          - relationships:
              to: ref('dim_location')
              field: location_id
      
      - name: sk_user_id
        tests:
          - relationships:
              to: ref('dim_user')
              field: sk_user_id
    